name: Redeploy Railway Service

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Railway Deployment
        run: |
          curl -X POST https://backboard.railway.com/graphql/v2 \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{ 
                "query": "mutation deploymentRestart { deploymentRestart(id: \"68a6bb6a-a871-4e9f-961a-251363532a11\") }"
              }'
