name: Redeploy Railway Service

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Railway Redeploy
  run: |
    curl -X POST https://backboard.railway.com/graphql/v2 \
    -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
    -H "Content-Type: application/json" \
    -d '{
          "query": "mutation deplo { 
            serviceInstanceDeployV2(
              environmentId: \"${{ secrets.RAILWAY_ENVIRONMENT_ID }}\", 
              serviceId: \"${{ secrets.RAILWAY_SERVICE_ID }}\"
            ) 
          }"
        }'
