name: Redeploy Railway Service

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Railway Deployment
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
          -d '{}' \
          "https://backboard.railway.app/v1/services/68a6bb6a-a871-4e9f-961a-251363532a11/deploy"